---
  - hosts: localhost
    vars:
      region: ap-southeast-2
    tasks:
    - name: Create centos ec2 instance
      ec2:
        instance_type: t2.micro
        image: ami-5b778339
        volumes:
        - device_name: /dev/sda1
          volume_size: 8
          volume_type: gp2
          delete_on_termination: true
        - device_name: /dev/sdb
          volume_size: 4
          volume_type: gp2
          delete_on_termination: true
          encrypted: true
        group_id: sg-2ae4514d
        region: "{{ region }}"
        user_data: |
                     #!/bin/sh
                     echo "{{ lookup('file', '/home/judd/.ssh/centos.pub') }}" >> /home/centos/.ssh/authorized_keys
                     restorecon -Rv ~/.ssh




